# Generated by Django 4.2.7 on 2023-11-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('orginal_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('desc', models.TextField(max_length=200)),
                ('composition', models.TextField(max_length=100)),
                ('category', models.CharField(choices=[('Laptop', 'LP'), ('Mouse', 'MS'), ('LAN', 'LN'), ('Tablet', 'TB'), ('Keyboard', 'KB')], max_length=10)),
                ('product_image', models.ImageField(upload_to='products')),
            ],
        ),
    ]
