# Generated by Django 4.2.7 on 2023-11-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_composition_product_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LP', 'Laptop'), ('MS', 'Mouse'), ('LN', 'LAN'), ('TB', 'Tablet'), ('KB', 'Keyboard')], max_length=10),
        ),
    ]
