# Generated by Django 4.2.7 on 2023-12-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_customer_zipcode_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='pro',
            new_name='products',
        ),
    ]
